/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/badge.glb --output src/components/catalog/hero/BadgeModel.tsx --types
*/

import { useGLTF } from "@react-three/drei";
import { useMemo } from "react";
import type { BufferGeometry, Mesh } from "three";

import { getFinishMaterialProps, type HeroFinish } from "./hero-finishes";

type BadgeGltf = {
  nodes: {
    model: Mesh & { geometry: BufferGeometry };
  };
};

useGLTF.preload("/models/badge.glb");

export function BadgeModel({ finish }: { finish: HeroFinish }) {
  const { nodes } = useGLTF("/models/badge.glb") as unknown as BadgeGltf;
  const material = useMemo(() => getFinishMaterialProps(finish), [finish]);

  return (
    <mesh geometry={nodes.model.geometry} castShadow receiveShadow>
      <meshPhysicalMaterial {...material} />
    </mesh>
  );
}
