/**
 * Scans public/catalog/products/{slug}/ sources and writes WebP/AVIF variants
 * plus src/data/catalog-image-manifest.ts for the app.
 *
 * Usage: pnpm images:optimize
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

import {
  CATALOG_PAGES,
  PRODUCT_FOLDER_SLUGS,
  type ProductCategory,
} from "../src/data/catalog-products.ts";
import type { CatalogImageManifest, ImageManifestEntry, ProductImageManifest } from "../src/data/catalog-image-types.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const PRODUCTS_ROOT = path.join(ROOT, "public/catalog/products");
const MANIFEST_OUT = path.join(ROOT, "src/data/catalog-image-manifest.ts");

const WEBP_WIDTHS = [480, 800, 1200] as const;
const AVIF_WIDTHS = [800, 1200] as const;
const SOURCE_EXTS = [".png", ".jpeg", ".jpg", ".webp"] as const;

type Role = "hero" | "mounted" | "detail" | "install";

function rolesForCategory(category: ProductCategory): Role[] {
  if (category === "installation") return ["hero", "install"];
  return ["hero", "mounted", "detail"];
}

async function findSource(folder: string, role: Role): Promise<string | null> {
  for (const ext of SOURCE_EXTS) {
    const file = path.join(folder, `${role}${ext}`);
    try {
      await fs.access(file);
      return file;
    } catch {
      /* try next ext */
    }
  }
  return null;
}

async function optimizeRole(
  slug: string,
  role: Role,
  sourcePath: string,
): Promise<ImageManifestEntry> {
  const outDir = path.join(PRODUCTS_ROOT, slug, "optimized");
  await fs.mkdir(outDir, { recursive: true });

  const meta = await sharp(sourcePath).metadata();
  const origWidth = meta.width ?? 1200;
  const origHeight = meta.height ?? 1500;

  const webpParts: string[] = [];
  const avifParts: string[] = [];
  let primaryWidth = Math.min(1200, origWidth);

  for (const w of WEBP_WIDTHS) {
    const width = Math.min(w, origWidth);
    const outName = `${role}-${width}.webp`;
    await sharp(sourcePath)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 82 })
      .toFile(path.join(outDir, outName));
    webpParts.push(`/catalog/products/${slug}/optimized/${outName} ${width}w`);
    if (width === Math.min(1200, origWidth)) primaryWidth = width;
  }

  for (const w of AVIF_WIDTHS) {
    const width = Math.min(w, origWidth);
    const outName = `${role}-${width}.avif`;
    await sharp(sourcePath)
      .resize({ width, withoutEnlargement: true })
      .avif({ quality: 65 })
      .toFile(path.join(outDir, outName));
    avifParts.push(`/catalog/products/${slug}/optimized/${outName} ${width}w`);
  }

  const blurBuffer = await sharp(sourcePath).resize(10).jpeg({ quality: 40 }).toBuffer();
  const blurDataURL = `data:image/jpeg;base64,${blurBuffer.toString("base64")}`;

  const height = Math.round((origHeight / origWidth) * primaryWidth);

  return {
    src: `/catalog/products/${slug}/optimized/${role}-${primaryWidth}.webp`,
    width: primaryWidth,
    height,
    blurDataURL,
    srcSetWebp: webpParts.join(", "),
    srcSetAvif: avifParts.join(", "),
  };
}

function writeManifest(manifest: CatalogImageManifest): string {
  return [
    `/** Generated by scripts/optimize-catalog-images.ts — do not edit manually. */`,
    `import type { CatalogImageManifest } from "./catalog-image-types";`,
    ``,
    `export const CATALOG_IMAGE_MANIFEST: CatalogImageManifest = ${JSON.stringify(manifest, null, 2)};`,
    ``,
  ].join("\n");
}

async function main() {
  const manifest: CatalogImageManifest = {};
  let optimized = 0;
  let skipped = 0;

  for (const product of CATALOG_PAGES) {
    const slug = PRODUCT_FOLDER_SLUGS[product.page];
    if (!slug) continue;

    const folder = path.join(PRODUCTS_ROOT, slug);
    const roles = rolesForCategory(product.category);
    const entry: Partial<ProductImageManifest> = {};

    for (const role of roles) {
      const source = await findSource(folder, role);
      if (!source) {
        console.warn(`[skip] ${slug}/${role} — no source file`);
        skipped++;
        continue;
      }
      entry[role] = await optimizeRole(slug, role, source);
      optimized++;
      console.log(`[ok] ${slug}/${role}`);
    }

    if (entry.hero) {
      manifest[slug] = entry as ProductImageManifest;
    } else {
      console.warn(`[warn] ${slug} — no hero image, excluded from manifest`);
    }
  }

  await fs.writeFile(MANIFEST_OUT, writeManifest(manifest), "utf8");
  console.log(`\nDone: ${optimized} roles optimized, ${skipped} skipped`);
  console.log(`Manifest: ${path.relative(ROOT, MANIFEST_OUT)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
