/** Generated by scripts/optimize-catalog-images.ts — do not edit manually. */
import type { CatalogImageManifest } from "./catalog-image-types";

export const CATALOG_IMAGE_MANIFEST: CatalogImageManifest = {
  "01-nh-12": {
    "hero": {
      "src": "/catalog/products/01-nh-12/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBv/EACEQAAEEAQMFAAAAAAAAAAAAAAEAAgMREgQFExQhIkGx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8Az+mO1iJnURTGSvItkofFHKIeV/HYZkcQTfb0koVUR//Z",
      "srcSetWebp": "/catalog/products/01-nh-12/optimized/hero-480.webp 480w, /catalog/products/01-nh-12/optimized/hero-800.webp 800w, /catalog/products/01-nh-12/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/01-nh-12/optimized/hero-800.avif 800w, /catalog/products/01-nh-12/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/01-nh-12/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAiEAACAQMDBQEAAAAAAAAAAAABAgMABREEEjEiM1JxodH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/AHnvkkUJVncyDOVXA2+24qSLxryO9L9/aK4IE1xCk7S2cciqaWuDYvVJx5UpH//Z",
      "srcSetWebp": "/catalog/products/01-nh-12/optimized/mounted-480.webp 480w, /catalog/products/01-nh-12/optimized/mounted-800.webp 800w, /catalog/products/01-nh-12/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/01-nh-12/optimized/mounted-800.avif 800w, /catalog/products/01-nh-12/optimized/mounted-1200.avif 1200w"
    }
  },
  "02-fm9": {
    "hero": {
      "src": "/catalog/products/02-fm9/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEF/8QAHRAAAgMAAgMAAAAAAAAAAAAAAQIAAxEEExVRYf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwDBp8Y9dCtTaHwdh7MBPz1B8itK+RalbgorkKd3RsNLKlGP/9k=",
      "srcSetWebp": "/catalog/products/02-fm9/optimized/hero-480.webp 480w, /catalog/products/02-fm9/optimized/hero-800.webp 800w, /catalog/products/02-fm9/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/02-fm9/optimized/hero-800.avif 800w, /catalog/products/02-fm9/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/02-fm9/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAHxABAAEDBQEBAAAAAAAAAAAAAQIAAxEEBSEiMUGh/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABYRAAMAAAAAAAAAAAAAAAAAAAACMf/aAAwDAQACEQMRAD8Ap3TVW7VyUZW7tsn2DhicfMeZazLqTL1/WmN9uzNQJJEiYR84oEgJnLTJA2p//9k=",
      "srcSetWebp": "/catalog/products/02-fm9/optimized/mounted-480.webp 480w, /catalog/products/02-fm9/optimized/mounted-800.webp 800w, /catalog/products/02-fm9/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/02-fm9/optimized/mounted-800.avif 800w, /catalog/products/02-fm9/optimized/mounted-1200.avif 1200w"
    }
  },
  "03-420": {
    "hero": {
      "src": "/catalog/products/03-420/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIDBv/EAB0QAAICAgMBAAAAAAAAAAAAAAECABEDEgQhQZH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/AMtjTjBQXLM1eMAL+RGGDY0CBfQ2uQhGiP/Z",
      "srcSetWebp": "/catalog/products/03-420/optimized/hero-480.webp 480w, /catalog/products/03-420/optimized/hero-800.webp 800w, /catalog/products/03-420/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/03-420/optimized/hero-800.avif 800w, /catalog/products/03-420/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/03-420/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQED/8QAHxAAAgEEAwEBAAAAAAAAAAAAAQIRAAQSIQMFcRQx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwCdt2q3jghSuKQZ1Pk0d90aAbXla95wJbXWCZMGUOczOzRg4kImP2qBpFe3/9k=",
      "srcSetWebp": "/catalog/products/03-420/optimized/mounted-480.webp 480w, /catalog/products/03-420/optimized/mounted-800.webp 800w, /catalog/products/03-420/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/03-420/optimized/mounted-800.avif 800w, /catalog/products/03-420/optimized/mounted-1200.avif 1200w"
    }
  },
  "04-460": {
    "hero": {
      "src": "/catalog/products/04-460/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAF/8QAHhAAAQQCAwEAAAAAAAAAAAAAAQACAxEEEwUSYRT/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/AMTEh4/5G7WtkkIJJ7kEeV5SLJBjbHdQWizQ2A0gqTRH/9k=",
      "srcSetWebp": "/catalog/products/04-460/optimized/hero-480.webp 480w, /catalog/products/04-460/optimized/hero-800.webp 800w, /catalog/products/04-460/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/04-460/optimized/hero-800.avif 800w, /catalog/products/04-460/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/04-460/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgT/xAAjEAACAQMBCQAAAAAAAAAAAAABAhEAAwQFEhMVISIxQVGB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABcRAAMBAAAAAAAAAAAAAAAAAAABAiH/2gAMAwEAAhEDEQA/AJNPzXZbeMRcYM6kKGADGRE0lGpZMDbsKG8gdpoTp91+IY3VyNwCPtMt+/ulPRKP/9k=",
      "srcSetWebp": "/catalog/products/04-460/optimized/mounted-480.webp 480w, /catalog/products/04-460/optimized/mounted-800.webp 800w, /catalog/products/04-460/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/04-460/optimized/mounted-800.avif 800w, /catalog/products/04-460/optimized/mounted-1200.avif 1200w"
    }
  },
  "05-440": {
    "hero": {
      "src": "/catalog/products/05-440/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBv/EAB0QAAICAwADAAAAAAAAAAAAAAECABEDBCETQVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAEREv/aAAwDAQACEQMRAD8Azurj18SLkyEO9WFHa+Qfct2PiXp9CpExIQUTFxWBymf/2Q==",
      "srcSetWebp": "/catalog/products/05-440/optimized/hero-480.webp 480w, /catalog/products/05-440/optimized/hero-800.webp 800w, /catalog/products/05-440/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/05-440/optimized/hero-800.avif 800w, /catalog/products/05-440/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/05-440/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAIRAAAgEDAwUAAAAAAAAAAAAAAQIAAwURBBIhIjFBkeH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABgRAAMBAQAAAAAAAAAAAAAAAAABAhEh/9oADAMBAAIRAxEAPwBrxdVqhggYbkUle3j7M+dSmTy3qLcXarWAc56RJhPJlENYFS6f/9k=",
      "srcSetWebp": "/catalog/products/05-440/optimized/mounted-480.webp 480w, /catalog/products/05-440/optimized/mounted-800.webp 800w, /catalog/products/05-440/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/05-440/optimized/mounted-800.avif 800w, /catalog/products/05-440/optimized/mounted-1200.avif 1200w"
    }
  },
  "06-480": {
    "hero": {
      "src": "/catalog/products/06-480/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQG/8QAHBAAAgIDAQEAAAAAAAAAAAAAAQIAEQMEIRKR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwDN4E1FQHI7M9DgYAX8h82v7ag4F8F3IYiox//Z",
      "srcSetWebp": "/catalog/products/06-480/optimized/hero-480.webp 480w, /catalog/products/06-480/optimized/hero-800.webp 800w, /catalog/products/06-480/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/06-480/optimized/hero-800.avif 800w, /catalog/products/06-480/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/06-480/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAJBAAAQMDAQkAAAAAAAAAAAAAAQACAwQFEhMRFCJBYWKBkaH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwCdyrhHPNgJo9biezIEE+ETvbe9br44vrzt5MA+IzTb19q4H//Z",
      "srcSetWebp": "/catalog/products/06-480/optimized/mounted-480.webp 480w, /catalog/products/06-480/optimized/mounted-800.webp 800w, /catalog/products/06-480/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/06-480/optimized/mounted-800.avif 800w, /catalog/products/06-480/optimized/mounted-1200.avif 1200w"
    }
  },
  "07-volvo-fh12": {
    "hero": {
      "src": "/catalog/products/07-volvo-fh12/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQEG/8QAHxAAAgECBwAAAAAAAAAAAAAAAQIABBEDFDFBUVPh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABAhH/2gAMAwEAAhEDEQA/AMzgrSkXZ3RrX5ERWopAoGZ0HV7At5Y1WAc6f//Z",
      "srcSetWebp": "/catalog/products/07-volvo-fh12/optimized/hero-480.webp 480w, /catalog/products/07-volvo-fh12/optimized/hero-800.webp 800w, /catalog/products/07-volvo-fh12/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/07-volvo-fh12/optimized/hero-800.avif 800w, /catalog/products/07-volvo-fh12/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/07-volvo-fh12/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgMF/8QAIBAAAQQBBQEBAAAAAAAAAAAAAQIDBBEABRITISKBkf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AIRdXmNub0SBw9eTR+ZsKm6gpRUGdoJuuUdYRQ4UtECvF1jOM4pUZpRNkoBP5jSP/9k=",
      "srcSetWebp": "/catalog/products/07-volvo-fh12/optimized/mounted-480.webp 480w, /catalog/products/07-volvo-fh12/optimized/mounted-800.webp 800w, /catalog/products/07-volvo-fh12/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/07-volvo-fh12/optimized/mounted-800.avif 800w, /catalog/products/07-volvo-fh12/optimized/mounted-1200.avif 1200w"
    }
  },
  "08-eev": {
    "hero": {
      "src": "/catalog/products/08-eev/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAD/8QAHhABAAEDBQEAAAAAAAAAAAAAAQIAAwQREiExUaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAABES/9oADAMBAAIRAxEAPwATHs488J3WCV0jwmonXL9o6ctJyDoax3PrVS0Mf//Z",
      "srcSetWebp": "/catalog/products/08-eev/optimized/hero-480.webp 480w, /catalog/products/08-eev/optimized/hero-800.webp 800w, /catalog/products/08-eev/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/08-eev/optimized/hero-800.avif 800w, /catalog/products/08-eev/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/08-eev/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAkEAACAQIDCQAAAAAAAAAAAAABAgMAEQQFEhQhMWFikqGxwf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAEC/9oADAMBAAIRAxEAPwBOZTyRYhwURJXGqytfdwvyv8qMXJJN/NNzueRcaSrWIiX2akbXL09oqs0V/9k=",
      "srcSetWebp": "/catalog/products/08-eev/optimized/mounted-480.webp 480w, /catalog/products/08-eev/optimized/mounted-800.webp 800w, /catalog/products/08-eev/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/08-eev/optimized/mounted-800.avif 800w, /catalog/products/08-eev/optimized/mounted-1200.avif 1200w"
    }
  },
  "09-i-shift": {
    "hero": {
      "src": "/catalog/products/09-i-shift/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEF/8QAHRAAAgICAwEAAAAAAAAAAAAAAQIDEQAEEhMxcf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAYEQEAAwEAAAAAAAAAAAAAAAABAAIhMf/aAAwDAQACEQMRAD8AxdTW0kiR5T2uy3xBIo/cHJtFZHEbMEBIUXdDBhiPCRkxlk5A1F2f/9k=",
      "srcSetWebp": "/catalog/products/09-i-shift/optimized/hero-480.webp 480w, /catalog/products/09-i-shift/optimized/hero-800.webp 800w, /catalog/products/09-i-shift/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/09-i-shift/optimized/hero-800.avif 800w, /catalog/products/09-i-shift/optimized/hero-1200.avif 1200w"
    }
  },
  "10-500": {
    "hero": {
      "src": "/catalog/products/10-500/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgEF/8QAIBAAAQQCAQUAAAAAAAAAAAAAAQACAxEEEiEFIkGRof/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAAQIR/9oADAMBAAIRAxEAPwAziwwHulLiB4HH1a7I+haN3yJA6hYD+L9I5Z1qzVqJqsA50//Z",
      "srcSetWebp": "/catalog/products/10-500/optimized/hero-480.webp 480w, /catalog/products/10-500/optimized/hero-800.webp 800w, /catalog/products/10-500/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/10-500/optimized/hero-800.avif 800w, /catalog/products/10-500/optimized/hero-1200.avif 1200w"
    }
  },
  "11-euro-4": {
    "hero": {
      "src": "/catalog/products/11-euro-4/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIG/8QAHxABAAIBBAMBAAAAAAAAAAAAAQIDAAQREiEiMUFh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AMrTVp7JRiyt5J8gOTbXXG2ZCNhEkhy97fuIFhp94eLxOzrDWq2zVVZOIf/Z",
      "srcSetWebp": "/catalog/products/11-euro-4/optimized/hero-480.webp 480w, /catalog/products/11-euro-4/optimized/hero-800.webp 800w, /catalog/products/11-euro-4/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/11-euro-4/optimized/hero-800.avif 800w, /catalog/products/11-euro-4/optimized/hero-1200.avif 1200w"
    }
  },
  "12-euro-5": {
    "hero": {
      "src": "/catalog/products/12-euro-5/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACAQAAEEAQQDAAAAAAAAAAAAAAEAAgMRIQQFE0ExUWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAEREjH/2gAMAwEAAhEDEQA/AMxpoGUySVxEZNZFX7ynHb3qGOLY+IMBpo424HXSmzk0BeB4+ISdgMp9P//Z",
      "srcSetWebp": "/catalog/products/12-euro-5/optimized/hero-480.webp 480w, /catalog/products/12-euro-5/optimized/hero-800.webp 800w, /catalog/products/12-euro-5/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/12-euro-5/optimized/hero-800.avif 800w, /catalog/products/12-euro-5/optimized/hero-1200.avif 1200w"
    }
  },
  "13-euro-6": {
    "hero": {
      "src": "/catalog/products/13-euro-6/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgIF/8QAIBAAAQMEAgMAAAAAAAAAAAAAAgABAwQRISISFUFRcf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQEBAQEAAAAAAAAAAAAAAAABAAIR/9oADAMBAAIRAxEAPwA/TQ0YAxlIUps1+OBa/paXfQjqMEdmw2qOt5+KUzXIORv/2Q==",
      "srcSetWebp": "/catalog/products/13-euro-6/optimized/hero-480.webp 480w, /catalog/products/13-euro-6/optimized/hero-800.webp 800w, /catalog/products/13-euro-6/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/13-euro-6/optimized/hero-800.avif 800w, /catalog/products/13-euro-6/optimized/hero-1200.avif 1200w"
    }
  },
  "14-460-mg": {
    "hero": {
      "src": "/catalog/products/14-460-mg/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQT/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMAERIEMUEGEyFRYf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAC/9oADAMBAAIRAxEAPwAHT6XRiJCweeYi7KGso+e6Yj6VhmjSTu4ZgNiAfF+KhjAWAYgDbamo5HEa2dthzSCnpS//2Q==",
      "srcSetWebp": "/catalog/products/14-460-mg/optimized/hero-480.webp 480w, /catalog/products/14-460-mg/optimized/hero-800.webp 800w, /catalog/products/14-460-mg/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/14-460-mg/optimized/hero-800.avif 800w, /catalog/products/14-460-mg/optimized/hero-1200.avif 1200w"
    }
  },
  "15-540": {
    "hero": {
      "src": "/catalog/products/15-540/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQG/8QAHhAAAgICAgMAAAAAAAAAAAAAAQIAAxESMUEEISL/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAR/9oADAMBAAIRAxEAPwDM1J4WqF7LA2v0BjmGsqDEI7a59ZHUmTqDyYxyKbf/2Q==",
      "srcSetWebp": "/catalog/products/15-540/optimized/hero-480.webp 480w, /catalog/products/15-540/optimized/hero-800.webp 800w, /catalog/products/15-540/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/15-540/optimized/hero-800.avif 800w, /catalog/products/15-540/optimized/hero-1200.avif 1200w"
    }
  },
  "16-fh": {
    "hero": {
      "src": "/catalog/products/16-fh/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBv/EABwQAAICAwEBAAAAAAAAAAAAAAECABEDBCExE//EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/AM9rrojArO+T6n0Cqimz0xCkUDzkkHkIhyKbf//Z",
      "srcSetWebp": "/catalog/products/16-fh/optimized/hero-480.webp 480w, /catalog/products/16-fh/optimized/hero-800.webp 800w, /catalog/products/16-fh/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/16-fh/optimized/hero-800.avif 800w, /catalog/products/16-fh/optimized/hero-1200.avif 1200w"
    }
  },
  "17-volvo": {
    "hero": {
      "src": "/catalog/products/17-volvo/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQP/xAAeEAABAwUBAQAAAAAAAAAAAAABAAIRAwQSMVETkv/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAXEQADAQAAAAAAAAAAAAAAAAAAAQIR/9oADAMBAAIRAxEAPwAG2p2+LS6ocjEjHSR8rLrflA0yY2qSelImDc6f/9k=",
      "srcSetWebp": "/catalog/products/17-volvo/optimized/hero-480.webp 480w, /catalog/products/17-volvo/optimized/hero-800.webp 800w, /catalog/products/17-volvo/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/17-volvo/optimized/hero-800.avif 800w, /catalog/products/17-volvo/optimized/hero-1200.avif 1200w"
    }
  },
  "18-xf-daf": {
    "hero": {
      "src": "/catalog/products/18-xf-daf/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBv/EACQQAAIBAgMJAAAAAAAAAAAAAAECAwAREiExBAUTFCMyobHR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABESH/2gAMAwEAAhEDEQA/AMtAdnwLxYmZhrhYi4+0p8BdisRC3yBOgq/dYBVbi/Ut4op1HMSZDuPunAN6f//Z",
      "srcSetWebp": "/catalog/products/18-xf-daf/optimized/hero-480.webp 480w, /catalog/products/18-xf-daf/optimized/hero-800.webp 800w, /catalog/products/18-xf-daf/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/18-xf-daf/optimized/hero-800.avif 800w, /catalog/products/18-xf-daf/optimized/hero-1200.avif 1200w"
    }
  },
  "19-i-save": {
    "hero": {
      "src": "/catalog/products/19-i-save/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBv/EAB4QAAICAgIDAAAAAAAAAAAAAAECAxEAEgQTIUGx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAWEQEBAQAAAAAAAAAAAAAAAAAAASH/2gAMAwEAAhEDEQA/AM7DDwVjRpeyRiLI3Cj5eTSNxux9I2C2aG3rE2aq/GDlXA//2Q==",
      "srcSetWebp": "/catalog/products/19-i-save/optimized/hero-480.webp 480w, /catalog/products/19-i-save/optimized/hero-800.webp 800w, /catalog/products/19-i-save/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/19-i-save/optimized/hero-800.avif 800w, /catalog/products/19-i-save/optimized/hero-1200.avif 1200w"
    }
  },
  "20-750": {
    "hero": {
      "src": "/catalog/products/20-750/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwb/xAAfEAEAAgEDBQAAAAAAAAAAAAABAAIRAwQSEyFBgdH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJeu20eA8r3v5AwHuG6Bl+xBekd2HmUH/9k=",
      "srcSetWebp": "/catalog/products/20-750/optimized/hero-480.webp 480w, /catalog/products/20-750/optimized/hero-800.webp 800w, /catalog/products/20-750/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/20-750/optimized/hero-800.avif 800w, /catalog/products/20-750/optimized/hero-1200.avif 1200w"
    }
  },
  "21-install-l": {
    "hero": {
      "src": "/catalog/products/21-install-l/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIF/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIDEQAhBBIiMUGR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEBAQEAAAAAAAAAAAAAAAABAgAh/9oADAMBAAIRAxEAPwDG48Ea8SORIVk2Oq6thX3zrWEk5hWRlRu0EgavWDWR1QqHYA+gcnHNJpsC93//2Q==",
      "srcSetWebp": "/catalog/products/21-install-l/optimized/hero-480.webp 480w, /catalog/products/21-install-l/optimized/hero-800.webp 800w, /catalog/products/21-install-l/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/21-install-l/optimized/hero-800.avif 800w, /catalog/products/21-install-l/optimized/hero-1200.avif 1200w"
    }
  },
  "22-install-v": {
    "hero": {
      "src": "/catalog/products/22-install-v/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQF/8QAHhAAAQMEAwAAAAAAAAAAAAAAAQACAwQRQXESIYH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwDAoI6QwudUN5O3Y+aURlsSAwEYJyhJ07aSUyP/2Q==",
      "srcSetWebp": "/catalog/products/22-install-v/optimized/hero-480.webp 480w, /catalog/products/22-install-v/optimized/hero-800.webp 800w, /catalog/products/22-install-v/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/22-install-v/optimized/hero-800.avif 800w, /catalog/products/22-install-v/optimized/hero-1200.avif 1200w"
    }
  },
  "23-install-iv": {
    "hero": {
      "src": "/catalog/products/23-install-iv/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAE/8QAHhABAAIBBAMAAAAAAAAAAAAAAQACEQMEBTESIXH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAGBEAAgMAAAAAAAAAAAAAAAAAAAERElH/2gAMAwEAAhEDEQA/ACNDR2px9LFat/HKpn3MjyFxSt0Doz1Dy1gwKH2UScArp//Z",
      "srcSetWebp": "/catalog/products/23-install-iv/optimized/hero-480.webp 480w, /catalog/products/23-install-iv/optimized/hero-800.webp 800w, /catalog/products/23-install-iv/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/23-install-iv/optimized/hero-800.avif 800w, /catalog/products/23-install-iv/optimized/hero-1200.avif 1200w"
    }
  },
  "24-install-vi": {
    "hero": {
      "src": "/catalog/products/24-install-vi/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAC/8QAIBAAAQMCBwAAAAAAAAAAAAAAAQACEQQSAxMUIUGR8P/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwAGnwqTRB7iMyDIPJjw6RzrbjB2lYkqTKnH/9k=",
      "srcSetWebp": "/catalog/products/24-install-vi/optimized/hero-480.webp 480w, /catalog/products/24-install-vi/optimized/hero-800.webp 800w, /catalog/products/24-install-vi/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/24-install-vi/optimized/hero-800.avif 800w, /catalog/products/24-install-vi/optimized/hero-1200.avif 1200w"
    }
  },
  "25-hub-steel": {
    "hero": {
      "src": "/catalog/products/25-hub-steel/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAD/8QAHBAAAgMBAAMAAAAAAAAAAAAAAQIAAyEEBRFB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8AGp4fHtz1EPY7sAXc4iH1ozYS1aBiBYCAfkzlKoj/2Q==",
      "srcSetWebp": "/catalog/products/25-hub-steel/optimized/hero-480.webp 480w, /catalog/products/25-hub-steel/optimized/hero-800.webp 800w, /catalog/products/25-hub-steel/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/25-hub-steel/optimized/hero-800.avif 800w, /catalog/products/25-hub-steel/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/25-hub-steel/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAID/8QAIhAAAQMDAwUAAAAAAAAAAAAAAQACAwQRFAUhMRJRYXGB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AMsysbBLURzkRMAJB5d9HCoalUEXyZd/KHGxppjG4dQjFwSd/R7ohe66C//Z",
      "srcSetWebp": "/catalog/products/25-hub-steel/optimized/mounted-480.webp 480w, /catalog/products/25-hub-steel/optimized/mounted-800.webp 800w, /catalog/products/25-hub-steel/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/25-hub-steel/optimized/mounted-800.avif 800w, /catalog/products/25-hub-steel/optimized/mounted-1200.avif 1200w"
    }
  },
  "26-hub-black": {
    "hero": {
      "src": "/catalog/products/26-hub-black/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIEBv/EAB0QAAIBBAMAAAAAAAAAAAAAAAABEQIDEiEjQVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAC/9oADAMBAAIRAxEAPwDJ8dOOKnSmfexncoThPRMAjSRQb//Z",
      "srcSetWebp": "/catalog/products/26-hub-black/optimized/hero-480.webp 480w, /catalog/products/26-hub-black/optimized/hero-800.webp 800w, /catalog/products/26-hub-black/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/26-hub-black/optimized/hero-800.avif 800w, /catalog/products/26-hub-black/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/26-hub-black/optimized/mounted-1122.webp",
      "width": 1122,
      "height": 1402,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAHxAAAgEEAgMAAAAAAAAAAAAAAQIDAAURIQQxEkFh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ABLhJnmzyMHTzkY4PfegamNgHA38rXc3LuGcBiR7FGGZ8ndB/9k=",
      "srcSetWebp": "/catalog/products/26-hub-black/optimized/mounted-480.webp 480w, /catalog/products/26-hub-black/optimized/mounted-800.webp 800w, /catalog/products/26-hub-black/optimized/mounted-1122.webp 1122w",
      "srcSetAvif": "/catalog/products/26-hub-black/optimized/mounted-800.avif 800w, /catalog/products/26-hub-black/optimized/mounted-1122.avif 1122w"
    }
  }
};
