/** Generated by scripts/optimize-catalog-images.ts — do not edit manually. */
import type { CatalogImageManifest } from "./catalog-image-types";

export const CATALOG_IMAGE_MANIFEST: CatalogImageManifest = {
  "01-nh-12": {
    "hero": {
      "src": "/catalog/products/01-nh-12/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgQFBv/EACAQAAEDAwUBAAAAAAAAAAAAAAEAAgMEETESISIyQVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAR/9oADAMBAAIRAxEAPwDNxU9PEGvllEpNjoZ8zuUyaxl+LXAeC+FOj6oUxyCbf//Z",
      "srcSetWebp": "/catalog/products/01-nh-12/optimized/hero-480.webp 480w, /catalog/products/01-nh-12/optimized/hero-800.webp 800w, /catalog/products/01-nh-12/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/01-nh-12/optimized/hero-800.avif 800w, /catalog/products/01-nh-12/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/01-nh-12/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAiEAACAQMDBQEAAAAAAAAAAAABAgMABREEEjEiM1JxodH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/AHnvkkUJVncyDOVXA2+24qSLxryO9L9/aK4IE1xCk7S2cciqaWuDYvVJx5UpH//Z",
      "srcSetWebp": "/catalog/products/01-nh-12/optimized/mounted-480.webp 480w, /catalog/products/01-nh-12/optimized/mounted-800.webp 800w, /catalog/products/01-nh-12/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/01-nh-12/optimized/mounted-800.avif 800w, /catalog/products/01-nh-12/optimized/mounted-1200.avif 1200w"
    },
    "package": {
      "src": "/catalog/products/01-nh-12/optimized/package-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EAB0QAAICAwADAAAAAAAAAAAAAAECACEDBBIFESL/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8ANj8fqPrkZeGa2JBsTNOE7blfn3VxzaJDEgmT4H//2Q==",
      "srcSetWebp": "/catalog/products/01-nh-12/optimized/package-480.webp 480w, /catalog/products/01-nh-12/optimized/package-800.webp 800w, /catalog/products/01-nh-12/optimized/package-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/01-nh-12/optimized/package-800.avif 800w, /catalog/products/01-nh-12/optimized/package-1200.avif 1200w"
    }
  },
  "02-fm9": {
    "hero": {
      "src": "/catalog/products/02-fm9/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQIG/8QAIBAAAQMEAgMAAAAAAAAAAAAAAQACEgMEETETISJRgf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAAf/aAAwDAQACEQMRAD8AzttRshHmFR5iCQHY79a0h7Labo0DHPXmoZr4hIa//9k=",
      "srcSetWebp": "/catalog/products/02-fm9/optimized/hero-480.webp 480w, /catalog/products/02-fm9/optimized/hero-800.webp 800w, /catalog/products/02-fm9/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/02-fm9/optimized/hero-800.avif 800w, /catalog/products/02-fm9/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/02-fm9/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAHxABAAEDBQEBAAAAAAAAAAAAAQIAAxEEBSEiMUGh/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABYRAAMAAAAAAAAAAAAAAAAAAAACMf/aAAwDAQACEQMRAD8Ap3TVW7VyUZW7tsn2DhicfMeZazLqTL1/WmN9uzNQJJEiYR84oEgJnLTJA2p//9k=",
      "srcSetWebp": "/catalog/products/02-fm9/optimized/mounted-480.webp 480w, /catalog/products/02-fm9/optimized/mounted-800.webp 800w, /catalog/products/02-fm9/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/02-fm9/optimized/mounted-800.avif 800w, /catalog/products/02-fm9/optimized/mounted-1200.avif 1200w"
    }
  },
  "03-420": {
    "hero": {
      "src": "/catalog/products/03-420/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBv/EACAQAAIBBAEFAAAAAAAAAAAAAAECAAMEESESEyIxQVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAEC/9oADAMBAAIRAxEAPwDN0ba16YarUdm45KrrefEYbUE9tQhfQ0cCTqTxEPJ+mOBp/9k=",
      "srcSetWebp": "/catalog/products/03-420/optimized/hero-480.webp 480w, /catalog/products/03-420/optimized/hero-800.webp 800w, /catalog/products/03-420/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/03-420/optimized/hero-800.avif 800w, /catalog/products/03-420/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/03-420/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQED/8QAHxAAAgEEAwEBAAAAAAAAAAAAAQIRAAQSIQMFcRQx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEBAQEAAAAAAAAAAAAAAAABABEh/9oADAMBAAIRAxEAPwCdt2q3jghSuKQZ1Pk0d90aAbXla95wJbXWCZMGUOczOzRg4kImP2qBpFe3/9k=",
      "srcSetWebp": "/catalog/products/03-420/optimized/mounted-480.webp 480w, /catalog/products/03-420/optimized/mounted-800.webp 800w, /catalog/products/03-420/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/03-420/optimized/mounted-800.avif 800w, /catalog/products/03-420/optimized/mounted-1200.avif 1200w"
    },
    "package": {
      "src": "/catalog/products/03-420/optimized/package-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQF/8QAIxAAAQMDAgcAAAAAAAAAAAAAAQIDBAARMQUSEyEjMkFSkf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAWEQEBAQAAAAAAAAAAAAAAAAACABL/2gAMAwEAAhEDEQA/AD0WJGdiErZbK0nuI50ioz6lEoFkk3A4nj5Ulylg7TbOKwVSH9x6zmfY0CGpSs3/2Q==",
      "srcSetWebp": "/catalog/products/03-420/optimized/package-480.webp 480w, /catalog/products/03-420/optimized/package-800.webp 800w, /catalog/products/03-420/optimized/package-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/03-420/optimized/package-800.avif 800w, /catalog/products/03-420/optimized/package-1200.avif 1200w"
    }
  },
  "04-460": {
    "hero": {
      "src": "/catalog/products/04-460/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EABwQAAIDAQADAAAAAAAAAAAAAAECAAMRMQQSIf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAAAAQL/2gAMAwEAAhEDEQA/AMwlXjqgLE2PmkA/BHFro9RqLyThwQoJzscDT//Z",
      "srcSetWebp": "/catalog/products/04-460/optimized/hero-480.webp 480w, /catalog/products/04-460/optimized/hero-800.webp 800w, /catalog/products/04-460/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/04-460/optimized/hero-800.avif 800w, /catalog/products/04-460/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/04-460/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgT/xAAjEAACAQMBCQAAAAAAAAAAAAABAhEAAwQFEhMVISIxQVGB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABcRAAMBAAAAAAAAAAAAAAAAAAABAiH/2gAMAwEAAhEDEQA/AJNPzXZbeMRcYM6kKGADGRE0lGpZMDbsKG8gdpoTp91+IY3VyNwCPtMt+/ulPRKP/9k=",
      "srcSetWebp": "/catalog/products/04-460/optimized/mounted-480.webp 480w, /catalog/products/04-460/optimized/mounted-800.webp 800w, /catalog/products/04-460/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/04-460/optimized/mounted-800.avif 800w, /catalog/products/04-460/optimized/mounted-1200.avif 1200w"
    },
    "package": {
      "src": "/catalog/products/04-460/optimized/package-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAED/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIAAxESEyIxUWGR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABgRAQEAAwAAAAAAAAAAAAAAAAEAAiIx/9oADAMBAAIRAxEAPwB9AXirYpuWOuPsO13UceZaHdUAVmA9GYnvCydSQ63/2Q==",
      "srcSetWebp": "/catalog/products/04-460/optimized/package-480.webp 480w, /catalog/products/04-460/optimized/package-800.webp 800w, /catalog/products/04-460/optimized/package-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/04-460/optimized/package-800.avif 800w, /catalog/products/04-460/optimized/package-1200.avif 1200w"
    }
  },
  "05-440": {
    "hero": {
      "src": "/catalog/products/05-440/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAEDBv/EAB8QAAIBBAIDAAAAAAAAAAAAAAECMQADBBIRITJBkf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAAf/aAAwDAQACEQMRAD8AzdvFsaqWZnPHYWOflNrGNsfOfRoUnSTFRM0xr//Z",
      "srcSetWebp": "/catalog/products/05-440/optimized/hero-480.webp 480w, /catalog/products/05-440/optimized/hero-800.webp 800w, /catalog/products/05-440/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/05-440/optimized/hero-800.avif 800w, /catalog/products/05-440/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/05-440/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAIRAAAgEDAwUAAAAAAAAAAAAAAQIAAwURBBIhIjFBkeH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABgRAAMBAQAAAAAAAAAAAAAAAAABAhEh/9oADAMBAAIRAxEAPwBrxdVqhggYbkUle3j7M+dSmTy3qLcXarWAc56RJhPJlENYFS6f/9k=",
      "srcSetWebp": "/catalog/products/05-440/optimized/mounted-480.webp 480w, /catalog/products/05-440/optimized/mounted-800.webp 800w, /catalog/products/05-440/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/05-440/optimized/mounted-800.avif 800w, /catalog/products/05-440/optimized/mounted-1200.avif 1200w"
    },
    "package": {
      "src": "/catalog/products/05-440/optimized/package-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACIQAAIBAwIHAAAAAAAAAAAAAAECAwARkQQFEhMUMUFSYf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AW2XRaafbxz4IzItzewue+aznTz+I2xVAMyQgIxUfDagcb+zZqD//2Q==",
      "srcSetWebp": "/catalog/products/05-440/optimized/package-480.webp 480w, /catalog/products/05-440/optimized/package-800.webp 800w, /catalog/products/05-440/optimized/package-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/05-440/optimized/package-800.avif 800w, /catalog/products/05-440/optimized/package-1200.avif 1200w"
    }
  },
  "06-480": {
    "hero": {
      "src": "/catalog/products/06-480/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgEG/8QAGxAAAgMBAQEAAAAAAAAAAAAAAREAAgMEMYH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzGfLic3fWzXgEJ58WVa6+QVJXssQ/9k=",
      "srcSetWebp": "/catalog/products/06-480/optimized/hero-480.webp 480w, /catalog/products/06-480/optimized/hero-800.webp 800w, /catalog/products/06-480/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/06-480/optimized/hero-800.avif 800w, /catalog/products/06-480/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/06-480/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAJBAAAQMDAQkAAAAAAAAAAAAAAQACAwQFEhMRFCJBYWKBkaH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwCdyrhHPNgJo9biezIEE+ETvbe9br44vrzt5MA+IzTb19q4H//Z",
      "srcSetWebp": "/catalog/products/06-480/optimized/mounted-480.webp 480w, /catalog/products/06-480/optimized/mounted-800.webp 800w, /catalog/products/06-480/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/06-480/optimized/mounted-800.avif 800w, /catalog/products/06-480/optimized/mounted-1200.avif 1200w"
    },
    "package": {
      "src": "/catalog/products/06-480/optimized/package-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAdEAACAgIDAQAAAAAAAAAAAAABAgMRAAQTFDFB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwA+to6nWjbhDMwF0ciSUJHAAAs/cbHNKsMYWRwKHjHJrkl2sn3DDr//2Q==",
      "srcSetWebp": "/catalog/products/06-480/optimized/package-480.webp 480w, /catalog/products/06-480/optimized/package-800.webp 800w, /catalog/products/06-480/optimized/package-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/06-480/optimized/package-800.avif 800w, /catalog/products/06-480/optimized/package-1200.avif 1200w"
    }
  },
  "07-volvo-fh12": {
    "hero": {
      "src": "/catalog/products/07-volvo-fh12/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAb/xAAeEAEAAQQCAwAAAAAAAAAAAAABAgADBBEFIRJBYf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAAAAQL/2gAMAwEAAhEDEQA/AJm1iWJQJTvy9OiNKOPxEHzu9/SgRXRTBdHdKBp//9k=",
      "srcSetWebp": "/catalog/products/07-volvo-fh12/optimized/hero-480.webp 480w, /catalog/products/07-volvo-fh12/optimized/hero-800.webp 800w, /catalog/products/07-volvo-fh12/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/07-volvo-fh12/optimized/hero-800.avif 800w, /catalog/products/07-volvo-fh12/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/07-volvo-fh12/optimized/mounted-1122.webp",
      "width": 1122,
      "height": 1402,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIEBv/EACEQAAIBAwQDAQAAAAAAAAAAAAECAwAEEhEhMWEFE0FV/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8ADJcXOAkvArFQSikgcdAVZ65v0WHWPFZSTydxA2KYaABRqvylM8khzY7tuatH/9k=",
      "srcSetWebp": "/catalog/products/07-volvo-fh12/optimized/mounted-480.webp 480w, /catalog/products/07-volvo-fh12/optimized/mounted-800.webp 800w, /catalog/products/07-volvo-fh12/optimized/mounted-1122.webp 1122w",
      "srcSetAvif": "/catalog/products/07-volvo-fh12/optimized/mounted-800.avif 800w, /catalog/products/07-volvo-fh12/optimized/mounted-1122.avif 1122w"
    },
    "package": {
      "src": "/catalog/products/07-volvo-fh12/optimized/package-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIF/8QAHhAAAgEFAAMAAAAAAAAAAAAAAQIDAAQREiETMWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAh/9oADAMBAAIRAxEAPwBdhAkljF5I1JbudayprjWaQKFwGIHPtGSaVXwsrgY9BjVkAk8orhMNv//Z",
      "srcSetWebp": "/catalog/products/07-volvo-fh12/optimized/package-480.webp 480w, /catalog/products/07-volvo-fh12/optimized/package-800.webp 800w, /catalog/products/07-volvo-fh12/optimized/package-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/07-volvo-fh12/optimized/package-800.avif 800w, /catalog/products/07-volvo-fh12/optimized/package-1200.avif 1200w"
    }
  },
  "08-eev": {
    "hero": {
      "src": "/catalog/products/08-eev/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgP/xAAgEAACAQQBBQAAAAAAAAAAAAABAgMABBEhMQUSIkGR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEBAQEAAAAAAAAAAAAAAAABAAIR/9oADAMBAAIRAxEAPwA3FHbLGD5O5XOzgA+xqlEB6YLeMNFCWCjJ7Rs4olFwtVLNnk/aY0tnb//Z",
      "srcSetWebp": "/catalog/products/08-eev/optimized/hero-480.webp 480w, /catalog/products/08-eev/optimized/hero-800.webp 800w, /catalog/products/08-eev/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/08-eev/optimized/hero-800.avif 800w, /catalog/products/08-eev/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/08-eev/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAkEAACAQIDCQAAAAAAAAAAAAABAgMAEQQFEhQhMWFikqGxwf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAEC/9oADAMBAAIRAxEAPwBOZTyRYhwURJXGqytfdwvyv8qMXJJN/NNzueRcaSrWIiX2akbXL09oqs0V/9k=",
      "srcSetWebp": "/catalog/products/08-eev/optimized/mounted-480.webp 480w, /catalog/products/08-eev/optimized/mounted-800.webp 800w, /catalog/products/08-eev/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/08-eev/optimized/mounted-800.avif 800w, /catalog/products/08-eev/optimized/mounted-1200.avif 1200w"
    }
  },
  "09-i-shift": {
    "hero": {
      "src": "/catalog/products/09-i-shift/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgEF/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIAAwQRQQUSMYGR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8AP10Y2OyG24Wt5KV8e5pHq1YOkRlXgd29D5D4l2YxyCbf/9k=",
      "srcSetWebp": "/catalog/products/09-i-shift/optimized/hero-480.webp 480w, /catalog/products/09-i-shift/optimized/hero-800.webp 800w, /catalog/products/09-i-shift/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/09-i-shift/optimized/hero-800.avif 800w, /catalog/products/09-i-shift/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/09-i-shift/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIhAAAgIBAgcBAAAAAAAAAAAAAQMCEQAEMQUGEyEzQnGh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAAQIh/9oADAMBAAIRAxEAPwCuv4stjFSdpp9MrIAJIo3vWFB4rxNOa+ZnTg5NH1rv9wQamdbR/cJk1On/2Q==",
      "srcSetWebp": "/catalog/products/09-i-shift/optimized/mounted-480.webp 480w, /catalog/products/09-i-shift/optimized/mounted-800.webp 800w, /catalog/products/09-i-shift/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/09-i-shift/optimized/mounted-800.avif 800w, /catalog/products/09-i-shift/optimized/mounted-1200.avif 1200w"
    }
  },
  "10-500": {
    "hero": {
      "src": "/catalog/products/10-500/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMEBv/EAB0QAAICAQUAAAAAAAAAAAAAAAACAQQREyFEYZL/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAERAv/aAAwDAQACEQMRAD8Ay6pWXEs7N1Gw3Xpxx29kIBJwLzT/2Q==",
      "srcSetWebp": "/catalog/products/10-500/optimized/hero-480.webp 480w, /catalog/products/10-500/optimized/hero-800.webp 800w, /catalog/products/10-500/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/10-500/optimized/hero-800.avif 800w, /catalog/products/10-500/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/10-500/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQMF/8QAHRAAAQQDAQEAAAAAAAAAAAAAAQIDBBEAEiETUf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDdkSRHRsGXXaNaoTd4mJHUdi0mz3uDqvJG6ekfSTlRRANYH//Z",
      "srcSetWebp": "/catalog/products/10-500/optimized/mounted-480.webp 480w, /catalog/products/10-500/optimized/mounted-800.webp 800w, /catalog/products/10-500/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/10-500/optimized/mounted-800.avif 800w, /catalog/products/10-500/optimized/mounted-1200.avif 1200w"
    }
  },
  "11-euro-4": {
    "hero": {
      "src": "/catalog/products/11-euro-4/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBv/EACAQAAEDAwUBAAAAAAAAAAAAAAIAAREDEiEEBTJRkbH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzdLbwNmI6rx0Iz9TD0VC8rQJhnDOeY8VA8UJD//Z",
      "srcSetWebp": "/catalog/products/11-euro-4/optimized/hero-480.webp 480w, /catalog/products/11-euro-4/optimized/hero-800.webp 800w, /catalog/products/11-euro-4/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/11-euro-4/optimized/hero-800.avif 800w, /catalog/products/11-euro-4/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/11-euro-4/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAgEAABBAAHAQAAAAAAAAAAAAABAAIDEQQSITFBYXGB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwX/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/AJ8crjVlg9NIxijWyQRtHF/UJoEjK3TpAVZdv//Z",
      "srcSetWebp": "/catalog/products/11-euro-4/optimized/mounted-480.webp 480w, /catalog/products/11-euro-4/optimized/mounted-800.webp 800w, /catalog/products/11-euro-4/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/11-euro-4/optimized/mounted-800.avif 800w, /catalog/products/11-euro-4/optimized/mounted-1200.avif 1200w"
    }
  },
  "12-euro-5": {
    "hero": {
      "src": "/catalog/products/12-euro-5/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAb/xAAcEAEAAgIDAQAAAAAAAAAAAAABAhEAAxQhQaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhEDEQA/AJWGiDTPYN01Ev75iOFqeywfMNF7MYLR3igV/9k=",
      "srcSetWebp": "/catalog/products/12-euro-5/optimized/hero-480.webp 480w, /catalog/products/12-euro-5/optimized/hero-800.webp 800w, /catalog/products/12-euro-5/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/12-euro-5/optimized/hero-800.avif 800w, /catalog/products/12-euro-5/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/12-euro-5/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFBv/EAB8QAQABBAEFAAAAAAAAAAAAAAECAAMEESEUMTJi0f/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAYEQADAQEAAAAAAAAAAAAAAAAAAQIRIf/aAAwDAQACEQMRAD8AMPOtRhuUzx2g80wZOMg9Tlc+h8rPWJOqtDoA7FNc9Dh6j//Z",
      "srcSetWebp": "/catalog/products/12-euro-5/optimized/mounted-480.webp 480w, /catalog/products/12-euro-5/optimized/mounted-800.webp 800w, /catalog/products/12-euro-5/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/12-euro-5/optimized/mounted-800.avif 800w, /catalog/products/12-euro-5/optimized/mounted-1200.avif 1200w"
    }
  },
  "13-euro-6": {
    "hero": {
      "src": "/catalog/products/13-euro-6/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQFBv/EAB4QAAIBBAMBAAAAAAAAAAAAAAECAAMEERIFUnHh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQADAAAAAAAAAAAAAAAAAAIAEUH/2gAMAwEAAhEDEQA/AMqKVuCNqznxPsbV+L1GbdicdzJcMZVZAjez/9k=",
      "srcSetWebp": "/catalog/products/13-euro-6/optimized/hero-480.webp 480w, /catalog/products/13-euro-6/optimized/hero-800.webp 800w, /catalog/products/13-euro-6/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/13-euro-6/optimized/hero-800.avif 800w, /catalog/products/13-euro-6/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/13-euro-6/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFBv/EAB0QAQACAgIDAAAAAAAAAAAAAAEAAgMEERITMVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFxEBAQEBAAAAAAAAAAAAAAAAAgASQf/aAAwDAQACEQMRAD8Aynhw1TvnH6UqsZrk0CoOsrx77SdCMvPII6v/2Q==",
      "srcSetWebp": "/catalog/products/13-euro-6/optimized/mounted-480.webp 480w, /catalog/products/13-euro-6/optimized/mounted-800.webp 800w, /catalog/products/13-euro-6/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/13-euro-6/optimized/mounted-800.avif 800w, /catalog/products/13-euro-6/optimized/mounted-1200.avif 1200w"
    }
  },
  "14-460-mg": {
    "hero": {
      "src": "/catalog/products/14-460-mg/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQG/8QAHhAAAgICAgMAAAAAAAAAAAAAAQIAEQMEEiExUYH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAEC/9oADAMBAAIRAxEAPwDMphxBksHJ4LAGvkobX1ORpHAv3AvQFRxwNP/Z",
      "srcSetWebp": "/catalog/products/14-460-mg/optimized/hero-480.webp 480w, /catalog/products/14-460-mg/optimized/hero-800.webp 800w, /catalog/products/14-460-mg/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/14-460-mg/optimized/hero-800.avif 800w, /catalog/products/14-460-mg/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/14-460-mg/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQEE/8QAIRAAAQQBAwUAAAAAAAAAAAAAAQACAxEEFSHREjFScqL/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABURAQEAAAAAAAAAAAAAAAAAAAAS/9oADAMBAAIRAxEAPwA/BypIGARTsjLhZaTusskrTI62tcbNmu6e0LGBvrl29eFdDxvOT54VKGX/2Q==",
      "srcSetWebp": "/catalog/products/14-460-mg/optimized/mounted-480.webp 480w, /catalog/products/14-460-mg/optimized/mounted-800.webp 800w, /catalog/products/14-460-mg/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/14-460-mg/optimized/mounted-800.avif 800w, /catalog/products/14-460-mg/optimized/mounted-1200.avif 1200w"
    }
  },
  "15-540": {
    "hero": {
      "src": "/catalog/products/15-540/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAG/8QAIBAAAgIBAwUAAAAAAAAAAAAAAQIAAxEEElEhIjFBYf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAAQIR/9oADAMBAAIRAxEAPwDKrTXgHubp65iVaaAVqGqUtgZP2GKTt8yyeYkClp//2Q==",
      "srcSetWebp": "/catalog/products/15-540/optimized/hero-480.webp 480w, /catalog/products/15-540/optimized/hero-800.webp 800w, /catalog/products/15-540/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/15-540/optimized/hero-800.avif 800w, /catalog/products/15-540/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/15-540/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1491,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIEBf/EACAQAAIBAwQDAAAAAAAAAAAAAAECAAMREgQTUXFTkZL/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ALTrVRyRTAaociFbL1x1H3X8T/MylruqrjZehaHfqcyg/9k=",
      "srcSetWebp": "/catalog/products/15-540/optimized/mounted-480.webp 480w, /catalog/products/15-540/optimized/mounted-800.webp 800w, /catalog/products/15-540/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/15-540/optimized/mounted-800.avif 800w, /catalog/products/15-540/optimized/mounted-1200.avif 1200w"
    }
  },
  "16-fh": {
    "hero": {
      "src": "/catalog/products/16-fh/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgX/xAAfEAACAQQCAwAAAAAAAAAAAAABAiEAAwQSFDEiQXL/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABYRAQEBAAAAAAAAAAAAAAAAAAACAf/aAAwDAQACEQMRAD8AO27eIgUMGZtAzEt7pNj3F49qVXwEaiIomva/IqsjHRZPVOU7x//Z",
      "srcSetWebp": "/catalog/products/16-fh/optimized/hero-480.webp 480w, /catalog/products/16-fh/optimized/hero-800.webp 800w, /catalog/products/16-fh/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/16-fh/optimized/hero-800.avif 800w, /catalog/products/16-fh/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/16-fh/optimized/mounted-1122.webp",
      "width": 1122,
      "height": 1402,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQb/xAAiEAACAQMCBwAAAAAAAAAAAAABAgADBBEFIRITMTJScdH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8ABt0JdSGVidsL9lMuq0Cozbt085KWx46gHb6jvMYbZh1qOIX/2Q==",
      "srcSetWebp": "/catalog/products/16-fh/optimized/mounted-480.webp 480w, /catalog/products/16-fh/optimized/mounted-800.webp 800w, /catalog/products/16-fh/optimized/mounted-1122.webp 1122w",
      "srcSetAvif": "/catalog/products/16-fh/optimized/mounted-800.avif 800w, /catalog/products/16-fh/optimized/mounted-1122.avif 1122w"
    }
  },
  "17-volvo": {
    "hero": {
      "src": "/catalog/products/17-volvo/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQMG/8QAIBAAAgIBAwUAAAAAAAAAAAAAAQIAAxEEBRIhMTJRcf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAYEQEBAAMAAAAAAAAAAAAAAAABAAIRMf/aAAwDAQACEQMRAD8AzVOnrWtbbHVhnwVup++ouu/uihVVQAMAAdoEpPGTiHUHEe3/2Q==",
      "srcSetWebp": "/catalog/products/17-volvo/optimized/hero-480.webp 480w, /catalog/products/17-volvo/optimized/hero-800.webp 800w, /catalog/products/17-volvo/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/17-volvo/optimized/hero-800.avif 800w, /catalog/products/17-volvo/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/17-volvo/optimized/mounted-1122.webp",
      "width": 1122,
      "height": 1402,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQEE/8QAIRAAAgIBAgcAAAAAAAAAAAAAAQIAERIDBAUhIjEyUnH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AFXfkhjSCzdYiaF4icB06fb0hjKMz9lGu6gKAtDl4iB//2Q==",
      "srcSetWebp": "/catalog/products/17-volvo/optimized/mounted-480.webp 480w, /catalog/products/17-volvo/optimized/mounted-800.webp 800w, /catalog/products/17-volvo/optimized/mounted-1122.webp 1122w",
      "srcSetAvif": "/catalog/products/17-volvo/optimized/mounted-800.avif 800w, /catalog/products/17-volvo/optimized/mounted-1122.avif 1122w"
    }
  },
  "18-xf-daf": {
    "hero": {
      "src": "/catalog/products/18-xf-daf/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIG/8QAHRAAAgICAwEAAAAAAAAAAAAAAQIAAwQhERMiUf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAXEQADAQAAAAAAAAAAAAAAAAAAAQIR/9oADAMBAAIRAxEAPwDLrRStau9vonaBdgfeYmmZjKijrXQAgzyYieB1On//2Q==",
      "srcSetWebp": "/catalog/products/18-xf-daf/optimized/hero-480.webp 480w, /catalog/products/18-xf-daf/optimized/hero-800.webp 800w, /catalog/products/18-xf-daf/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/18-xf-daf/optimized/hero-800.avif 800w, /catalog/products/18-xf-daf/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/18-xf-daf/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAIhAAAgEDAwUBAAAAAAAAAAAAAQIDAAQREiFBBRMUMVHR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCgXskYPYS1gAGwEGTTsRYxJrILaRnjest05PLuoYpCwV2IOGPwnmlmEiMVFxLgHHsflQf/2Q==",
      "srcSetWebp": "/catalog/products/18-xf-daf/optimized/mounted-480.webp 480w, /catalog/products/18-xf-daf/optimized/mounted-800.webp 800w, /catalog/products/18-xf-daf/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/18-xf-daf/optimized/mounted-800.avif 800w, /catalog/products/18-xf-daf/optimized/mounted-1200.avif 1200w"
    }
  },
  "19-i-save": {
    "hero": {
      "src": "/catalog/products/19-i-save/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIDBv/EAB4QAAICAgIDAAAAAAAAAAAAAAECAAMEERJBEzJx/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwDP1YmEEraxrWJALAMB18k7KMXyNwWwLs623UVfQQxwa//Z",
      "srcSetWebp": "/catalog/products/19-i-save/optimized/hero-480.webp 480w, /catalog/products/19-i-save/optimized/hero-800.webp 800w, /catalog/products/19-i-save/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/19-i-save/optimized/hero-800.avif 800w, /catalog/products/19-i-save/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/19-i-save/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEC/8QAHxAAAgIBBAMAAAAAAAAAAAAAAQIDEQAEEjFBMkKR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANvNBHqNRMBsMrlqY8X0MMTrQ8cJyDPKCoNNyRfWTc49z8GIf//Z",
      "srcSetWebp": "/catalog/products/19-i-save/optimized/mounted-480.webp 480w, /catalog/products/19-i-save/optimized/mounted-800.webp 800w, /catalog/products/19-i-save/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/19-i-save/optimized/mounted-800.avif 800w, /catalog/products/19-i-save/optimized/mounted-1200.avif 1200w"
    }
  },
  "20-750": {
    "hero": {
      "src": "/catalog/products/20-750/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwb/xAAfEAEAAgEDBQAAAAAAAAAAAAABAAIRAwQSEyFBgdH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJeu20eA8r3v5AwHuG6Bl+xBekd2HmUH/9k=",
      "srcSetWebp": "/catalog/products/20-750/optimized/hero-480.webp 480w, /catalog/products/20-750/optimized/hero-800.webp 800w, /catalog/products/20-750/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/20-750/optimized/hero-800.avif 800w, /catalog/products/20-750/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/20-750/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQF/8QAIBAAAgEEAQUAAAAAAAAAAAAAAQIDAAQRIRITIzFBQv/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAEC/9oADAMBAAIRAxEAPwAT38MrdNO0qjChzsisqS94yMoaMgEjOTujej69+KgzVchY/9k=",
      "srcSetWebp": "/catalog/products/20-750/optimized/mounted-480.webp 480w, /catalog/products/20-750/optimized/mounted-800.webp 800w, /catalog/products/20-750/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/20-750/optimized/mounted-800.avif 800w, /catalog/products/20-750/optimized/mounted-1200.avif 1200w"
    }
  },
  "21-install-l": {
    "hero": {
      "src": "/catalog/products/21-install-l/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQMG/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIDEQAhEgQxM3GB/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABkRAAIDAQAAAAAAAAAAAAAAAAACAxESIf/aAAwDAQACEQMRAD8AESCNejjKRK5NcrAJawPvexrDpYSsrqnLiGIGr1lIXdUIDMACNA5oY/GvoY0Ue76C74P/2Q==",
      "srcSetWebp": "/catalog/products/21-install-l/optimized/hero-480.webp 480w, /catalog/products/21-install-l/optimized/hero-800.webp 800w, /catalog/products/21-install-l/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/21-install-l/optimized/hero-800.avif 800w, /catalog/products/21-install-l/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/21-install-l/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIRAAAgEDBAMBAAAAAAAAAAAAAQIDAAQRBRIx0SEiUeH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwCcthIkrI13lifn7WtNMvAigX+BjjYe6NuJxLcM7wxls8+3dIpqEpRTtQeOBnurSP/Z",
      "srcSetWebp": "/catalog/products/21-install-l/optimized/mounted-480.webp 480w, /catalog/products/21-install-l/optimized/mounted-800.webp 800w, /catalog/products/21-install-l/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/21-install-l/optimized/mounted-800.avif 800w, /catalog/products/21-install-l/optimized/mounted-1200.avif 1200w"
    }
  },
  "22-install-v": {
    "hero": {
      "src": "/catalog/products/22-install-v/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAeEAEAAgIDAAMAAAAAAAAAAAABAhEAAwQhMUFRYf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAABEQD/2gAMAwEAAhEDEQA/AIWnRqjx4jrGSFko9zX9+KyZshWyRC2ItP2YzkzmbEJSpey/cKrfriC4WO//2Q==",
      "srcSetWebp": "/catalog/products/22-install-v/optimized/hero-480.webp 480w, /catalog/products/22-install-v/optimized/hero-800.webp 800w, /catalog/products/22-install-v/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/22-install-v/optimized/hero-800.avif 800w, /catalog/products/22-install-v/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/22-install-v/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAHxABAAEEAwADAAAAAAAAAAAAAQIAAwQRISIxEkGB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAEA/9oADAMBAAIRAxEAPwCaWFkF17WOzs4fulY4mSRBuwHXh5Wec6cr8flatSYaBR3x+0yZFyQSU280Mhf/2Q==",
      "srcSetWebp": "/catalog/products/22-install-v/optimized/mounted-480.webp 480w, /catalog/products/22-install-v/optimized/mounted-800.webp 800w, /catalog/products/22-install-v/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/22-install-v/optimized/mounted-800.avif 800w, /catalog/products/22-install-v/optimized/mounted-1200.avif 1200w"
    }
  },
  "23-install-iv": {
    "hero": {
      "src": "/catalog/products/23-install-iv/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIRAAAgAGAQUAAAAAAAAAAAAAAQIAAwQREiEFMUFhcbH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGREBAAMBAQAAAAAAAAAAAAAAAQACAyEx/9oADAMBAAIRAxEAPwDEp6anNPKuqsWW5BG29Htv4Yg3HDI4zLrfR8QaRMcPiHYKeovqFgaEPlUfYGjYeM//2Q==",
      "srcSetWebp": "/catalog/products/23-install-iv/optimized/hero-480.webp 480w, /catalog/products/23-install-iv/optimized/hero-800.webp 800w, /catalog/products/23-install-iv/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/23-install-iv/optimized/hero-800.avif 800w, /catalog/products/23-install-iv/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/23-install-iv/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1491,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAHxAAAgEEAgMAAAAAAAAAAAAAAQIDAAQRIRIxIkGB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAVEQEBAAAAAAAAAAAAAAAAAAABAP/aAAwDAQACEQMRAD8AnayuBKfKAcjkaPulFs7kKAZUBx0OqzzXztOvKKJimACQc6+00LiRgGOMndGoX//Z",
      "srcSetWebp": "/catalog/products/23-install-iv/optimized/mounted-480.webp 480w, /catalog/products/23-install-iv/optimized/mounted-800.webp 800w, /catalog/products/23-install-iv/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/23-install-iv/optimized/mounted-800.avif 800w, /catalog/products/23-install-iv/optimized/mounted-1200.avif 1200w"
    }
  },
  "24-install-vi": {
    "hero": {
      "src": "/catalog/products/24-install-vi/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgQFBv/EACMQAQABBAECBwAAAAAAAAAAAAECAAMEESExQQUSIjJhkaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAERAgP/2gAMAwEAAhEDEQA/AImBZx23DzwJkjSJzJfntrn8oXC8SFLeNcYHtddTtSWPKQxBQXk31rQlyej1S+6bmqFpxn//2Q==",
      "srcSetWebp": "/catalog/products/24-install-vi/optimized/hero-480.webp 480w, /catalog/products/24-install-vi/optimized/hero-800.webp 800w, /catalog/products/24-install-vi/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/24-install-vi/optimized/hero-800.avif 800w, /catalog/products/24-install-vi/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/24-install-vi/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQb/xAAcEAACAgMBAQAAAAAAAAAAAAABAgMRAAQhMRL/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAEA/9oADAMBAAIRAxEAPwAyRnilKyPAjcJBmqrxldfeCjiDnn1kzJIZpw8gBYULr2sohsSsAS5s9w1C/9k=",
      "srcSetWebp": "/catalog/products/24-install-vi/optimized/mounted-480.webp 480w, /catalog/products/24-install-vi/optimized/mounted-800.webp 800w, /catalog/products/24-install-vi/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/24-install-vi/optimized/mounted-800.avif 800w, /catalog/products/24-install-vi/optimized/mounted-1200.avif 1200w"
    }
  },
  "25-hub-steel": {
    "hero": {
      "src": "/catalog/products/25-hub-steel/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEF/8QAHxAAAgEEAgMAAAAAAAAAAAAAAgMBAAURIUFhBBIT/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAWEQEBAQAAAAAAAAAAAAAAAAABAAL/2gAMAwEAAhEDEQA/ABW232ZvhibjMmSOSyWMTzHVZD0LF7BU8vnBTA86zrdGxHsvsakzuqZYJf/Z",
      "srcSetWebp": "/catalog/products/25-hub-steel/optimized/hero-480.webp 480w, /catalog/products/25-hub-steel/optimized/hero-800.webp 800w, /catalog/products/25-hub-steel/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/25-hub-steel/optimized/hero-800.avif 800w, /catalog/products/25-hub-steel/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/25-hub-steel/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIG/8QAHBAAAgIDAQEAAAAAAAAAAAAAAQIDIQAEERPR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8APaNZN0asZV1CFwPuQXgUkHWHRVA47PAjx+1rKp6HWjmck2pvRuuTZwylj//Z",
      "srcSetWebp": "/catalog/products/25-hub-steel/optimized/mounted-480.webp 480w, /catalog/products/25-hub-steel/optimized/mounted-800.webp 800w, /catalog/products/25-hub-steel/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/25-hub-steel/optimized/mounted-800.avif 800w, /catalog/products/25-hub-steel/optimized/mounted-1200.avif 1200w"
    }
  },
  "26-hub-black": {
    "hero": {
      "src": "/catalog/products/26-hub-black/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMG/8QAHBABAAICAwEAAAAAAAAAAAAAAQACESESEzFR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEBAQEAAAAAAAAAAAAAAAACAQAx/9oADAMBAAIRAxEAPwDKHXV0bPsUWUMXwQtg5+S0qFTzBGXf/9k=",
      "srcSetWebp": "/catalog/products/26-hub-black/optimized/hero-480.webp 480w, /catalog/products/26-hub-black/optimized/hero-800.webp 800w, /catalog/products/26-hub-black/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/26-hub-black/optimized/hero-800.avif 800w, /catalog/products/26-hub-black/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/26-hub-black/optimized/mounted-1200.webp",
      "width": 1200,
      "height": 1490,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQF/8QAHRAAAQQDAQEAAAAAAAAAAAAAAQIDBBEAEiExBf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCaNHjCK0laCpx0WFjuvL7mepLexsC7w430H24pbBFDwkdGKI6FAE2Sfe4H/9k=",
      "srcSetWebp": "/catalog/products/26-hub-black/optimized/mounted-480.webp 480w, /catalog/products/26-hub-black/optimized/mounted-800.webp 800w, /catalog/products/26-hub-black/optimized/mounted-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/26-hub-black/optimized/mounted-800.avif 800w, /catalog/products/26-hub-black/optimized/mounted-1200.avif 1200w"
    }
  },
  "27-hub-black-matte": {
    "hero": {
      "src": "/catalog/products/27-hub-black-matte/optimized/hero-1200.webp",
      "width": 1200,
      "height": 1200,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBv/EACAQAAEDAgcAAAAAAAAAAAAAAAEAAgMRQRMhIjJhcZH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFxEBAQEBAAAAAAAAAAAAAAAAAgABEv/aAAwDAQACEQMRAD8Ay0cUToAa6r8JGFJZjvETRmFe3aOkoGKNvm//2Q==",
      "srcSetWebp": "/catalog/products/27-hub-black-matte/optimized/hero-480.webp 480w, /catalog/products/27-hub-black-matte/optimized/hero-800.webp 800w, /catalog/products/27-hub-black-matte/optimized/hero-1200.webp 1200w",
      "srcSetAvif": "/catalog/products/27-hub-black-matte/optimized/hero-800.avif 800w, /catalog/products/27-hub-black-matte/optimized/hero-1200.avif 1200w"
    },
    "mounted": {
      "src": "/catalog/products/27-hub-black-matte/optimized/mounted-1122.webp",
      "width": 1122,
      "height": 1402,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIEBf/EACAQAAEEAgEFAAAAAAAAAAAAAAEAAgMhERJhBCJBUZH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzunjjlgDnl+XbdwIAZj2POVHkG7SGMXbr5Q1HP1B/9k=",
      "srcSetWebp": "/catalog/products/27-hub-black-matte/optimized/mounted-480.webp 480w, /catalog/products/27-hub-black-matte/optimized/mounted-800.webp 800w, /catalog/products/27-hub-black-matte/optimized/mounted-1122.webp 1122w",
      "srcSetAvif": "/catalog/products/27-hub-black-matte/optimized/mounted-800.avif 800w, /catalog/products/27-hub-black-matte/optimized/mounted-1122.avif 1122w"
    }
  }
};
